menu:
  Home: /
  Archives: /archives
  About: /about
  Projects: /projects

# duoshuo comment
duoshuo: true
duoshuo_name: leohxj

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: UA-42849828-1
